name: 'Linkhub check-in'
on:
  push:
  schedule:
    - cron: '0 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: 'Install requirements'
        run: 'python -m pip install --upgrade pip && pip install -r requirements.txt'
      - name: 'Run action'
        env: 
          HTTP_PROXY: ${{secrets.HTTP_PROXY}}
          HTTPS_PROXY: ${{secrets.HTTPS_PROXY}}
          ACCOUNT_EMAIL: ${{secrets.ACCOUNT_EMAIL}}
          ACCOUNT_PASSWORD: ${{secrets.ACCOUNT_PASSWORD}}
        run: 'python app.py'
